[env]
framework = arduino
monitor_speed = 115200
lib_deps =
    madhephaestus/ESP32Servo @ ^1.1.1
    bblanchon/ArduinoJson @ ^6.21.3
    knolleary/PubSubClient @ ^2.8
    adafruit/Adafruit LSM6DS @ ^4.7.0
    adafruit/Adafruit Unified Sensor @ ^1.1.14
    adafruit/Adafruit BME280 Library @ ^2.2.4
    adafruit/Adafruit BMP280 Library @ ^2.6.8
    adafruit/Adafruit NeoPixel @ ^1.11.0
    https://github.com/tzapu/WiFiManager.git

[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.psram_type = opi
board_upload.flash_size = 8MB
build_flags = 
    -D CORE_DEBUG_LEVEL=3
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D BOARD_HAS_PSRAM
    -D MQTT_MAX_PACKET_SIZE=1024
    -D BOARD_VARIANT=\"esp32s3\"
    -D PIN_I2C_ATMO_SDA=15
    -D PIN_I2C_ATMO_SCL=16
    -D PIN_I2C_SEIS_SDA=12
    -D PIN_I2C_SEIS_SCL=13

[env:esp32_wroom]
platform = espressif32
board = esp32dev
build_flags = 
    -D CORE_DEBUG_LEVEL=3
    -D MQTT_MAX_PACKET_SIZE=1024
    -D BOARD_VARIANT=\"esp32_wroom\"
    -D PIN_I2C_ATMO_SDA=21
    -D PIN_I2C_ATMO_SCL=22
    -D PIN_I2C_SEIS_SDA=18
    -D PIN_I2C_SEIS_SCL=19
